# Generated by OptiMIPS
# This file contains the optimized instruction order from the assembled program.
# If your original program used a .data section, keep/copy that data section as needed.
# Original CPI: 1.053 (1 stalls)
# Optimized CPI: 1.000 (0 stalls)

.text
.globl main
main:
    addi $s2, $zero, 0     # line 3: loop counter
    lui  $s0, 0x1001       # line 1: base address of data segment
    lw   $t0, 0($s0)       # line 6: load array value
    addi $s1, $zero, 8     # line 2: loop limit
    addi $s3, $zero, 0     # line 4: running sum
    sub  $t3, $s1, $s2     # line 9: independent filler candidate
    add  $t1, $t0, $s3     # line 7: load-use RAW hazard, reads $t0
    addi $t7, $zero, 3     # line 5: constant used in loop
    addi $s0, $s0, 4       # line 14: move to next array element
    add  $t2, $s2, $t7     # line 8: independent filler candidate
    addi $s2, $s2, 1       # line 15: increment counter
    and  $t4, $t1, $t2     # line 10: depends on $t1 and $t2
    bne  $s2, $s1, loop    # line 16: loop branch
    or   $t5, $t4, $t3     # line 11: depends on $t4 and $t3
    xor  $t6, $t5, $t0     # line 12: depends on $t5 and $t0
    add  $s3, $s3, $t6     # line 13: updates running sum
    sw   $s3, result       # line 17: store final sum
    add  $zero, $zero, $zero  # line 18: nop-style instruction
